spawn:
  x: -232
  y: 92
  z: -261
  world: world
  w: 6
  h: 3
  r: 90
  scale: 2
  collide: command
  strings:
    new:
      x: 33
      y: 10
      font: 0
      scale: 2
      align: 0
      text:
      - §5DraconicTechnoMagic
    warps:
      x: 30
      y: 40
      font: 0
      scale: 1
      align: 0
      text:
      - §5Варпы сервера
    links:
      x: 155
      y: 40
      font: 0
      scale: 1
      align: 0
      text:
      - §5Полезные ссылки
  images: {}
  tables: {}
  buttons:
    bt:
      x: 22
      y: 56
      w: 90
      h: 20
      text: §5Эндер Мир
      command: /warp end
    bt2:
      x: 22
      y: 80
      w: 90
      h: 20
      text: §5Карьерный мир
      command: /warp mine
    bt3:
      x: 22
      y: 104
      w: 90
      h: 20
      text: §5Мастерская
      command: /warp craft
    bt4:
      x: 155
      y: 56
      w: 90
      h: 20
      text: §5Экономика
      command: https://forum-six.u-studio.su/index.php?/topic/2-%D1%8D%D0%BA%D0%BE%D0%BD%D0%BE%D0%BC%D0%B8%D0%BA%D0%B0-draconictechnomagic/
    bt5:
      x: 155
      y: 80
      w: 90
      h: 20
      text: §5Магазин
      command: https://six.u-studio.su/shop?cat=items&server=DTM
    bt6:
      x: 155
      y: 104
      w: 90
      h: 20
      text: §5Донат
      command: https://six.u-studio.su/donate
flare:
  x: -233
  y: 93
  z: -254
  world: world
  w: 4
  h: 4
  r: 180
  scale: 2
  collide: command
  strings:
    new:
      x: 49
      y: 10
      font: 0
      scale: 2
      align: 0
      text:
      - §5Меню DTM
  images: {}
  tables: {}
  buttons:
    bt:
      x: 30
      y: 35
      w: 120
      h: 20
      text: §5Кейсы
      command: /jcases list
    bt1:
      x: 30
      y: 60
      w: 120
      h: 20
      text: §5Покупка кейсов
      command: /cases
    bt2:
      x: 30
      y: 85
      w: 120
      h: 20
      text: §5Онлайн-карта
      command: https://six.u-studio.su/dtm-map/
    bt3:
      x: 30
      y: 110
      w: 120
      h: 20
      text: §5Аукцион
      command: /ca
    bt4:
      x: 30
      y: 145
      w: 120
      h: 20
      text: §5Открыть меню
      command: /menu
town_plot_0_1:
  x: 3048
  y: 67
  z: 930
  world: world
  w: 3
  h: 2
  r: 90
  scale: 2
  collide: command
  strings:
    name:
      x: 21
      y: 10
      font: 0
      scale: 1
      align: 0
      text:
      - '§5Начальный дом #1'
    info:
      x: 5
      y: 30
      font: 0
      scale: 1
      align: 0
      text:
      - '§7Владелец: §5(Свободно)'
      - ''
      - §7Доступно для аренды
  images: {}
  tables: {}
  buttons:
    bt:
      x: 32
      y: 66
      w: 70
      h: 20
      text: §5Купить
      command: https://six.u-studio.su/shop?cat=rg&server=DTM&region=town_plot_0_1
town_plot_0_2:
  x: 3048
  y: 67
  z: 952
  world: world
  w: 3
  h: 2
  r: 90
  scale: 2
  collide: command
  strings:
    name:
      x: 21
      y: 10
      font: 0
      scale: 1
      align: 0
      text:
      - '§5Начальный дом #2'
    info:
      x: 5
      y: 30
      font: 0
      scale: 1
      align: 0
      text:
      - '§7Владелец: §5(Свободно)'
      - ''
      - §7Доступно для аренды
  images: {}
  tables: {}
  buttons:
    bt:
      x: 32
      y: 66
      w: 70
      h: 20
      text: §5Купить
      command: https://six.u-studio.su/shop?cat=rg&server=DTM&region=town_plot_0_2
town_plot_0_3:
  x: 3048
  y: 67
  z: 974
  world: world
  w: 3
  h: 2
  r: 90
  scale: 2
  collide: command
  strings:
    name:
      x: 21
      y: 10
      font: 0
      scale: 1
      align: 0
      text:
      - '§5Начальный дом #3'
    info:
      x: 5
      y: 30
      font: 0
      scale: 1
      align: 0
      text:
      - '§7Владелец: §5(Свободно)'
      - ''
      - §7Доступно для аренды
  images: {}
  tables: {}
  buttons:
    bt:
      x: 32
      y: 66
      w: 70
      h: 20
      text: §5Купить
      command: https://six.u-studio.su/shop?cat=rg&server=DTM&region=town_plot_0_3
town_plot_0_4:
  x: 3048
  y: 67
  z: 996
  world: world
  w: 3
  h: 2
  r: 90
  scale: 2
  collide: command
  strings:
    name:
      x: 15
      y: 10
      font: 0
      scale: 1
      align: 0
      text:
      - '§5Начальный дом #1'
    info:
      x: 5
      y: 30
      font: 0
      scale: 1
      align: 0
      text:
      - '§7Владелец: §5(Свободно)'
      - ''
      - §7Доступно для аренды
  images: {}
  tables: {}
  buttons:
    bt:
      x: 32
      y: 66
      w: 70
      h: 20
      text: §5Купить
      command: https://six.u-studio.su/shop?cat=rg&server=DTM&region=town_plot_0_4
town_plot_1_1:
  x: 3095
  y: 67
  z: 929
  world: world
  w: 3
  h: 2
  r: 90
  scale: 2
  collide: command
  strings:
    name:
      x: 28
      y: 10
      font: 0
      scale: 1
      align: 0
      text:
      - '§5Модерн дом #1'
    info:
      x: 5
      y: 30
      font: 0
      scale: 1
      align: 0
      text:
      - '§7Владелец: §5(Свободно)'
      - ''
      - §7Доступно для аренды
  images: {}
  tables: {}
  buttons:
    bt:
      x: 32
      y: 66
      w: 70
      h: 20
      text: §5Купить
      command: https://six.u-studio.su/shop?cat=rg&server=DTM&region=town_plot_1_1
town_plot_1_2:
  x: 3095
  y: 67
  z: 957
  world: world
  w: 3
  h: 2
  r: 90
  scale: 2
  collide: command
  strings:
    name:
      x: 28
      y: 10
      font: 0
      scale: 1
      align: 0
      text:
      - '§5Модерн дом #2'
    info:
      x: 5
      y: 30
      font: 0
      scale: 1
      align: 0
      text:
      - '§7Владелец: §5(Свободно)'
      - ''
      - §7Доступно для аренды
  images: {}
  tables: {}
  buttons:
    bt:
      x: 32
      y: 66
      w: 70
      h: 20
      text: §5Купить
      command: https://six.u-studio.su/shop?cat=rg&server=DTM&region=town_plot_1_2
town_plot_1_3:
  x: 3095
  y: 67
  z: 991
  world: world
  w: 3
  h: 2
  r: 90
  scale: 2
  collide: command
  strings:
    name:
      x: 28
      y: 10
      font: 0
      scale: 1
      align: 0
      text:
      - '§5Модерн дом #3'
    info:
      x: 5
      y: 30
      font: 0
      scale: 1
      align: 0
      text:
      - '§7Владелец: §5(Свободно)'
      - ''
      - §7Доступно для аренды
  images: {}
  tables: {}
  buttons:
    bt:
      x: 32
      y: 66
      w: 70
      h: 20
      text: §5Купить
      command: https://six.u-studio.su/shop?cat=rg&server=DTM&region=town_plot_1_3
town_plot_2_1:
  x: 3044
  y: 67
  z: 900
  world: world
  w: 3
  h: 2
  r: 90
  scale: 2
  collide: command
  strings:
    name:
      x: 15
      y: 10
      font: 0
      scale: 1
      align: 0
      text:
      - '§5Продвинутый дом #1'
    info:
      x: 5
      y: 30
      font: 0
      scale: 1
      align: 0
      text:
      - '§7Владелец: §5(Свободно)'
      - ''
      - §7Доступно для аренды
  images: {}
  tables: {}
  buttons:
    bt:
      x: 32
      y: 66
      w: 70
      h: 20
      text: §5Купить
      command: https://six.u-studio.su/shop?cat=rg&server=DTM&region=town_plot_2_1
town_plot_2_2:
  x: 3044
  y: 67
  z: 857
  world: world
  w: 3
  h: 2
  r: 90
  scale: 2
  collide: command
  strings:
    name:
      x: 15
      y: 10
      font: 0
      scale: 1
      align: 0
      text:
      - '§5Продвинутый дом #2'
    info:
      x: 5
      y: 30
      font: 0
      scale: 1
      align: 0
      text:
      - '§7Владелец: §5(Свободно)'
      - ''
      - §7Доступно для аренды
  images: {}
  tables: {}
  buttons:
    bt:
      x: 32
      y: 66
      w: 70
      h: 20
      text: §5Купить
      command: https://six.u-studio.su/shop?cat=rg&server=DTM&region=town_plot_2_2
town_plot_3_1:
  x: 3082
  y: 67
  z: 766
  world: world
  w: 3
  h: 2
  r: 180
  scale: 2
  collide: command
  strings:
    name:
      x: 35
      y: 10
      font: 0
      scale: 1
      align: 0
      text:
      - '§5Дом-база #1'
    info:
      x: 5
      y: 30
      font: 0
      scale: 1
      align: 0
      text:
      - '§7Владелец: §5MozG'
      - ''
      - '§7Арендован до: §515.03.2020'
  images: {}
  tables: {}
  buttons:
    bt:
      x: 32
      y: 66
      w: 70
      h: 20
      text: §5Управлять
      command: https://six.u-studio.su/shop?cat=rg&server=DTM
town_plot_3_2:
  x: -3207
  y: 70
  z: 4200
  world: spawn
  w: 3
  h: 3
  r: 180
  scale: 2
  collide: command
  strings:
    new:
      x: 27
      y: 20
      font: 0
      scale: 2
      align: 0
      text:
      - §bSkyTech
  images: []
  tables: []
  buttons:
    bt:
      x: 22
      y: 56
      w: 90
      h: 20
      text: §bСоздать остров
      command: /is
